"""Core Impressions functionality."""

from impressions.core.evaluation import (
    EchoEvaluator,
    EvaluationEngine,
    EvaluationEngineError,
    EvaluationResult,
    Evaluator,
)
from impressions.core.docker_executor import DockerPythonExecutor
from impressions.core.code_evaluator import CodeTaskEvaluator
from impressions.core.execution import CodeExecutor, ExecutionError, ExecutionResult
from impressions.core.failure_classification import FailureCategory, FailureClassification, classify_failure
from impressions.core.config import (
    ConfigError,
    CredentialsConfig,
    EvaluationConfig,
    ModelConfig,
    ProjectConfig,
    ProjectPaths,
    load_project_config,
)
from impressions.core.scoring import (
    AttemptResult,
    MultiAttemptEvaluator,
    MultiAttemptResult,
    ReliabilityMetrics,
    calculate_reliability_metrics,
)
from impressions.core.model_factory import create_model_client
from impressions.core.llm_evaluator import LLMEvaluator
from impressions.core.model_client import (
    ModelClient,
    ModelGenerationError,
    ModelRequest,
    ModelResponse,
)
from impressions.core.openai_client import OpenAIModelClient
from impressions.core.prompt_builder import (
    PromptBuilder,
    PromptBuilderError,
    PromptRenderResult,
)
from impressions.core.pytest_grader import GradingError, PytestCodeGrader
from impressions.core.reporting import (
    PersistedRun,
    RunComparison,
    RunMetadata,
    RunRegistry,
    RunRegistryError,
    RunSummary,
    compare_persisted_runs,
    load_persisted_run,
    render_terminal_report,
    render_terminal_comparison,
)
from impressions.core.tasks import (
    ParsedTask,
    Task,
    TaskDefinition,
    TaskDiscoveryError,
    TaskExpected,
    TaskExecution,
    TaskFieldError,
    TaskInput,
    TaskValidationError,
    discover_tasks,
    discover_tasks_from_config,
    load_task,
    load_tasks,
    load_tasks_from_config,
    parse_task,
    parse_task_data,
)

__all__ = [
    "EchoEvaluator",
    "ConfigError",
    "CodeExecutor",
    "CodeTaskEvaluator",
    "CredentialsConfig",
    "EvaluationConfig",
    "DockerPythonExecutor",
    "EvaluationEngine",
    "EvaluationEngineError",
    "EvaluationResult",
    "Evaluator",
    "ExecutionError",
    "ExecutionResult",
    "FailureCategory",
    "FailureClassification",
    "GradingError",
    "LLMEvaluator",
    "AttemptResult",
    "MultiAttemptEvaluator",
    "MultiAttemptResult",
    "ReliabilityMetrics",
    "ModelClient",
    "ModelConfig",
    "ModelGenerationError",
    "ModelRequest",
    "ModelResponse",
    "OpenAIModelClient",
    "ProjectConfig",
    "ProjectPaths",
    "ParsedTask",
    "PromptBuilder",
    "PromptBuilderError",
    "PromptRenderResult",
    "PersistedRun",
    "RunComparison",
    "PytestCodeGrader",
    "RunMetadata",
    "RunRegistry",
    "RunRegistryError",
    "RunSummary",
    "Task",
    "TaskDefinition",
    "TaskDiscoveryError",
    "TaskExpected",
    "TaskExecution",
    "TaskFieldError",
    "TaskInput",
    "TaskValidationError",
    "discover_tasks",
    "discover_tasks_from_config",
    "load_task",
    "load_project_config",
    "load_persisted_run",
    "compare_persisted_runs",
    "load_tasks",
    "load_tasks_from_config",
    "parse_task",
    "parse_task_data",
    "render_terminal_report",
    "render_terminal_comparison",
    "create_model_client",
    "classify_failure",
    "calculate_reliability_metrics",
]
